# Версия docker-compose
version: '3'
# Список наших сервисов (контейнеров)
services:
    auth-service:
      container_name: auth-service
      stdin_open: true
      build:
        context: auth
      command: npm run start:dev
      volumes:
        - ./auth/src:/app/src
      ports:
        - "6002:3002"
    user-service:
      container_name: users-service
      stdin_open: true
      build:
        context: users
      command: npm run start:dev
      volumes:
        - ./users/src:/app/src
      ports:
        - "6001:3001"
    post-service:
      container_name: posts-service
      stdin_open: true
      build:
        context: posts
      command: npm run start:dev
      volumes:
        - ./posts/src:/app/src
      ports:
        - "6003:3003"
    metadata-service:
      container_name: metadata-service
      stdin_open: true
      build:
        context: metadata
      command: npm run start:dev
      volumes:
        - ./metadata/src:/app/src
      ports:
        - "6004:3004"
    likes-service:
      container_name: likes-service
      stdin_open: true
      build:
        context: likes
      command: npm run start:dev
      volumes:
        - ./likes/src:/app/src
      ports:
        - "6005:3005"
    users-db:
      container_name: users-db
      image: postgres:12
      environment:
        POSTGRES_DB: "postgres-users-dev"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "root"
      ports:
        - "7432:5432"
    auth-db:
      container_name: auth-db
      image: postgres:12
      environment:
        POSTGRES_DB: "postgres-auth-dev"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "root"
      ports:
        - "6432:5432"
    posts-db:
      container_name: post-db
      image: postgres:12
      environment:
        POSTGRES_DB: "postgres-posts-dev"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "root"
      ports:
        - "8432:5432"
    metadata-db:
      container_name: metadata-db
      image: postgres:12
      environment:
        POSTGRES_DB: "postgres-metadata-dev"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "root"
      ports:
        - "9432:5432"
    likes-db:
      container_name: likes-db
      image: postgres:12
      environment:
        POSTGRES_DB: "postgres-likes-dev"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "root"
      ports:
        - "10432:5432"
    nginx:
        container_name: snappix-gateway
        stdin_open: true
        build:
          context: gateway
        # используем последний стабильный образ nginx
        image: nginx:latest
        # маршрутизируем порты
        ports:
            - "8080:80"
            - "7000:443"
        restart: always
        volumes:
            - ./gateway/nginx.conf:/etc/nginx/nginx.conf